### ISSUE TITLE
Please help in setup

### ISSUE THREAD

**Issue by pedant24** [Ross1337/SMSBotBypass#170]
26 passing (2s)
  1 failing

  1) Call.js
       /call POST
         it should return the callSid : everything's fine:
     ### **_Uncaught AssertionError: expected { Object (error) } to not have property 'error'_**
      at /root/SMSBotBypass/api/test/call.js:129:46
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:716:12)
      at /root/SMSBotBypass/api/node_modules/superagent/lib/node/index.js:916:18
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:19:7)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by pedant24** [comment]
My tg @Ped01an
