### ISSUE TITLE
HELP adding discord bot

### ISSUE THREAD

**Issue by denada070707** [Ross1337/SMSBotBypass#182]
Hello sir,  can you help me for adding discord bot
i already trying using my token and client secret key
and getting error like this

```
(node:251865) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/home/biel/my-projects/validator/SMSBotBypass/bots/discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:133:26)
    at Client.login (/home/biel/my-projects/validator/SMSBotBypass/bots/discord/node_modules/discord.js/src/client/Client.js:223:21)
(node:251865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:251865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

heres my config.js

```
module.exports = {
    apiurl: 'http://localhost:1337',
    apipassword: '',

    discordtoken: '151e10173240eaf945e922579556b**',
    discordprefix: '!',
    secretpassword: 'dIkuaAaHiEqWG***',
    botuser_rolename: 'Bot User',
    admin_rolename: 'Admin'
};
```

**Comment by Ross1337** [comment]
Hello, Your apiurl is wrong and your discord token too
