### ISSUE TITLE
help 400 bad request

### ISSUE THREAD

**Issue by sayhello819** [Ross1337/SMSBotBypass#183]
@Ross1337 
![image](https://user-images.githubusercontent.com/36510875/143303354-09a42690-af2d-4d6e-af99-32bccb5453b9.png)
hello ross , please help me for this . i have problem 400 bad request after i send call

**Comment by sayhello819** [comment]
Error: Request failed with status code 400
    at createError (/home/rizav20/SMSBotBypass/bots/discord/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/rizav20/SMSBotBypass/bots/discord/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/rizav20/SMSBotBypass/bots/discord/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
