### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by Mtrxkng33** [Ross1337/SMSBotBypass#187]
`
(node:16071) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/root/SMSBotBypass/bots/discord/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'DiscordAPIError',
  message: 'Missing Permissions',
  method: 'put',
  path:
   '/guilds/913169515343384596/members/902316268730867743/roles/913170293558767667',
  code: 50013,
  httpStatus: 403 }

Tried different API password ( Oauth2 discord api pw, personnal pw, api link oauth2 Ip api link with 1337 port ) still having issue.

@diegottesformel1 Telegram`

**Comment by Mtrxkng33** [comment]
call is proceeded but voice says "an application error has occured"

**Comment by Mtrxkng33** [comment]
![image](https://user-images.githubusercontent.com/95034231/143500657-a4803e03-2415-4f92-af6e-71a6c8408571.png)
![image](https://user-images.githubusercontent.com/95034231/143500687-13e3320f-9525-4d34-8134-ef344a0e2de5.png)

Everything is well configured but when call is made nothing happens and voice automation talks in english and says application error has occured.
