### ISSUE TITLE
Help Me 

### ISSUE THREAD

**Issue by giotihaxx** [Ross1337/SMSBotBypass#285]
Please Help me my telegram : @gozzoi

**Comment by giotihaxx** [comment]
26 passing (2s)
  1 failing

  1) Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'
      at /home/giotihax/Desktop/SMSBotBypass/api/test/call.js:129:46                              
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:716:12)                 
      at /home/giotihax/Desktop/SMSBotBypass/api/node_modules/superagent/lib/node/index.js:916:18 
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:19:7)      
      at endReadableNT (_stream_readable.js:1241:12)                                              
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by Mouha-Rida** [comment]
Same issue @Mouha_Rida

**Comment by Ross1337** [comment]
Added
