### ISSUE TITLE
Getting an Error 

### ISSUE THREAD

**Issue by Zendxokk** [Ross1337/SMSBotBypass#340]
const member = m.message.guild.member(user);
                                   ^

TypeError: Cannot read properties of null (reading 'member')
    at module.exports (/root/SMSBotBypass/bots/discord/commands/secret.js:45:36)
    at Statement.<anonymous> (/root/SMSBotBypass/bots/discord/bot.js:125:9)
    at Statement.replacement (/root/SMSBotBypass/bots/discord/node_modules/sqlite3/lib/trace.js:25:27)

Reason?

**Comment by david09baz** [comment]
on an admin cmd prompt execute: npm install discord.js and it will work

**Comment by Ross1337** [comment]
Give me your tg if you're still facing the issue
