### ISSUE TITLE
Ross I need your help please.

### ISSUE THREAD

**Issue by WealthyMindset** [Ross1337/SMSBotBypass#80]
Can you add me on Telegram: MARGIN_0

I would like some assistance in starting this up, I am a complete noob.

I will donate some crypto in return as a thank you.

Please tell me here what message you send me so I can verify its the real you.

**Comment by Ross1337** [comment]
Done

**Comment by darkhacknet** [comment]
> Done

Im totally stuck here... And as I told you I've set the roles and permissions but I don't know what happen. ![IMG_20211008_023635.jpg](https://user-images.githubusercontent.com/45680149/136517078-b68e610a-bb23-4110-91a0-6285e0dbc8e9.jpg)

**Comment by Ross1337** [comment]
You just need to do !secret yoursecretpassword , this password is in your config.js file

**Comment by darkhacknet** [comment]
> !secret is a command that can be used for anyone in order to get get the bot permissions if they got the secret password from the bot

Im getting this when I used !secret command ! 

㉿kaliLi)-[~/OtpBot/SMSBotBypass/bots/discord]
└─$ node bot.js                                                                                                                                                                                                                          1 ⨯
Logged in as CenCei OTP Bot#3409!
/home/xborland/OtpBot/SMSBotBypass/bots/discord/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'member' of null
    at module.exports (/home/xborland/OtpBot/SMSBotBypass/bots/discord/commands/secret.js:45:36)
    at Statement.<anonymous> (/home/xborland/OtpBot/SMSBotBypass/bots/discord/bot.js:125:9)
--> in Database#get('SELECT permissions FROM users WHERE userid = ?', [ '895783301372059709' ], [Function])
    at Client.<anonymous> (/home/xborland/OtpBot/SMSBotBypass/bots/discord/bot.js:77:8)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/xborland/OtpBot/SMSBotBypass/bots/discord/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/xborland/OtpBot/SMSBotBypass/bots/discord/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/xborland/OtpBot/SMSBotBypass/bots/discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/xborland/OtpBot/SMSBotBypass/bots/discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/xborland/OtpBot/SMSBotBypass/bots/discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/xborland/OtpBot/SMSBotBypass/bots/discord/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:314:20) {
  __augmented: true

weird !

**Comment by Ross1337** [comment]
Because your not using the good api url and your public port is not open

**Comment by Ross1337** [comment]
Check on google how to open a port on your router, your good api url is http://yourip:1337

**Comment by darkhacknet** [comment]
> So ?

Now just to test... I mové everything to a vps... Here you have my npm test. With all correct. ![Screenshot_2021-10-10-11-19-21-898_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/45680149/136704454-d500d5fd-81b5-4c1b-86da-fc498c1f3cff.jpg)

**Comment by darkhacknet** [comment]
> So ?

Then my bot is connected... ![IMG_20211010_112157.jpg](https://user-images.githubusercontent.com/45680149/136704554-7dd7b417-2820-4164-9ed8-9a7ce5dfcb96.jpg)

**Comment by darkhacknet** [comment]
> So ?

But at the end I have the same issue, mi config files seems to be good... I have set the ip of the vps... In the server and API url.. The port is 1337... And when I send a call command.... This is what I got..

Help command works..
Call command... Is not working..

![IMG_20211010_112546.jpg](https://user-images.githubusercontent.com/45680149/136704690-0c510f00-5762-4f4f-bbc5-97bf4ea3551a.jpg)

![Screenshot_2021-10-10-11-26-34-818_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/45680149/136704735-2dd2f9a6-21e9-4ee6-bba0-350b7632622b.jpg)

**Comment by darkhacknet** [comment]
> Is your port open ? I think that's the error

Its weird.. I have added the 1337 to the ip tables but the restrt command doesnt work... So when I try to test telnet on that port I have also connection refused. Im still trying.

**Comment by darkhacknet** [comment]
> On your router

Now im using a vps.. I will check how to open the port there..

**Comment by sofien00000** [comment]
> > You'll not be able to dit easily.
> 
> I really dont know how but its good to learn and also its funny. Thank you so much Ross. 🤜🤛
here you go bro don't know what to do
![Capture](https://user-images.githubusercontent.com/88594827/147517560-d165c83d-524a-4f18-b216-b45a9d7144a5.PNG)

**Comment by Ross1337** [comment]
> > > You'll not be able to dit easily.
> > 
> > 
> > I really dont know how but its good to learn and also its funny. Thank you so much Ross. 🤜🤛
> > here you go bro don't know what to do
> > ![Capture](https://user-images.githubusercontent.com/88594827/147517560-d165c83d-524a-4f18-b216-b45a9d7144a5.PNG)

As scrived : your phone number isn't good, it should look like +numbers
